name: Animated Profile
on:
  schedule:
    - cron: '0 0 * * *'  # Daily update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate 3D Contributions
      uses: yoshi389111/github-profile-3d-contrib@0.7.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: amarzeus
        
    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update animated visualization"
        branch: main