name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: amarzeus
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_achievements: yes