name: Generate 3D Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: amarzeus
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github&grid_size=20x10
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&grid_size=20x10
            dist/ocean.gif?color_snake=#7c3aed&color_dots=#0891b2,#0e7490,#155e75,#164e63,#083344&grid_size=20x10
            dist/github.gif?color_snake=#ff6b6b&color_dots=#c9f0ff,#73deff,#009ffd,#0062cc,#001d6e&grid_size=20x10
            dist/rainbow.gif?color_snake=#ffd700&color_dots=#ff0000,#ff8000,#ffff00,#80ff00,#00ff00,#00ff80,#00ffff,#0080ff,#0000ff,#8000ff,#ff00ff,#ff0080&grid_size=20x10

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}